server:
  port: 8080

spring:
  application:
    name: board-api
  docker:
    compose:
      # mvn spring-boot:run 시 docker-compose.yml 자동 기동
      # 앱 종료해도 DB는 유지
      lifecycle-management: start-only
      file: docker-compose.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: board
    password: board
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: debug
